---
kasten:
  kdrSecretKey: secret/data/hub/kastendr-passphrase

  policyDefaults:
    locationProfileName: my-location-profile  # Set to `name` of an available locationProfiles entry below
    presetName: daily-backup
    ignoreExceptions: false

  locationProfileDefaults:
    secretKey: secret/data/hub/aws-creds
    immutable: false
    protectionPeriod: 120h0m0s # 5 Days
    s3Region: us-east-1

  locationProfiles:
    location-profile-1:
      name: my-location-profile               
      secretKey: secret/data/hub/aws-creds    # Vault path for values-secret entry to be used for S3 auth
      bucketName: rhvp-test-bucket            # Replace with the AWS S3 bucket name to store backup data
      immutable: true                        # Set true only if AWS S3 bucket was created with Versioning/Object Lock enabled; otherwise false
      protectionPeriod: 168h0m0s # 7 Days     # Optional, override default immutablility period. Caution!
    location-profile-2:
      name: my-extra-profile
      secretKey: secret/data/hub/aws-creds    
      bucketName: rhvp-test-bucket-2